### ISSUE TITLE
Add redeem rate slider to funding cycle details card

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#500] opened 2022-02-09 05:10 UTC
Design thread:
https://discord.com/channels/775859454780244028/940660284979314819

## Proposal

Add a 'Redeem rate' (only if overflow > 0) to the funding cycle card, which would be a 'token amount' slider (based on % of total supply) followed by an ETH amount? The slider would represent 'amount of tokens being redeemed' and the ETH amount would be the ETH you'd receive by redeeming that amount of tokens (based on given token amount as % of the total supply, current overflow and bonding curve)

## More details

<img width="594" alt="Screen Shot 2022-02-09 at 3 06 46 pm" src="https://user-images.githubusercontent.com/96150256/153125650-4a39c2c0-f8f3-4655-ad86-b4d38b14b4cd.png">

Slider will sit under 'Issue rate'

**Comment by tomquirk** [comment] 2022-07-24 02:56
Closing, duplicate of https://github.com/jbx-protocol/juice-interface/issues/1219

**Closed** 2023-01-13 01:11 UTC
Labels: type:enhancement, soon, ux:contributor
