### ISSUE TITLE
Improve HTML semantics of project cards

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#393] opened 2022-01-18 01:14 UTC
## Description

Cards that link to projects aren't "links" (`<a>` HTML tags). This has a few accessibility implications, most notably that users can't right-click the card to open it in a new tab.

## Proposal

Make wrap the project cards in an unstyled `<a>` tag instead of `<div>`.

## Screenshots

These cards should be links, not `div`s
<img width="540" alt="Screen Shot 2022-01-18 at 10 43 21 am" src="https://user-images.githubusercontent.com/94939382/149853893-085382c1-3189-4df0-8e9a-7aaa5671074c.png">

**Comment by tomquirk** [comment] 2022-07-21 04:45
Re-opening this issue; there's been a regression since Next was merged.

@wraeth-eth could you please take a look?

**Comment by tomquirk** [comment] 2022-07-22 14:25
im on it

**Closed** 2022-07-22 16:02 UTC
Labels: type:bug, UX, severity:3, ux:contributor
