### ISSUE TITLE
v2 Project card doesn't have handle

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#991] opened 2022-05-12 14:00 UTC
## Description

_A clear and concise description of what could be better._

## Proposal

_A description of the change you'd like to see._

## Screenshots

<img width="488" alt="image" src="https://user-images.githubusercontent.com/33093632/168092991-1b72f944-8c99-4a79-b657-2f8d0dea3a4f.png">

**Comment by jmilldotdev** [comment] 2022-05-12 14:18
Guess this isn't a bug since v2 projects don't have handles, but curious if ya'll think a placeholder is necessary or if it's fine as-is.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/33093632/168096693-904c5e6b-9b8c-4628-ba34-200290a0bccf.png">

**Comment by aeolianeth** [comment] 2022-05-16 23:39
@jmilldotdev I think we can add something like this for now 🤷 

<img width="121" alt="Screen Shot 2022-05-17 at 9 09 39 am" src="https://user-images.githubusercontent.com/94939382/168699303-b12f80dd-04d9-47aa-b2be-b543762052ee.png">

**Comment by aeolianeth** [comment] 2022-07-03 10:37
@peripheralist could you pls check if https://github.com/jbx-protocol/juice-interface/pull/1185 will close this issue? 🙏

**Comment by peripheralist** [comment] 2022-07-08 18:43
sorry just realized this is in fact not a bug—if a project has a defined handle it'll show up. i'm cool with closing this, unless we wanted to add the project ID if there's no handle? doesn't seem necessary to me

![Image](https://user-images.githubusercontent.com/79433522/178051858-faf45d14-684b-4209-a8fb-c3b575424ccb.png)

**Comment by jmilldotdev** [comment] 2022-07-08 19:03
yeah we can close this, i thought it was a bug at the time and didn't realize that was the case for v2 projects.

**Closed** 2022-07-11 20:56 UTC
Labels: bug, severity::3
