### ISSUE TITLE
"In Juicebox" chart is displaying incorrect data.

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2179] opened 2022-10-10 23:05 UTC
## Summary

<img width="406" alt="Screen Shot 2022-10-11 at 9 33 56 AM" src="https://user-images.githubusercontent.com/12551741/194964986-43f411d9-aa53-4710-84fa-1cda299e278e.png">

## Steps to reproduce

1. Go to https://juicebox.money/@mcsa
2. Click on **In Juicebox** on the volume chart
3. Observe. The In JUicebox number is inaccurate

## What is the _current_ bug behavior?

**In Juicebox** chart is inaccurate.

## What is the expected _correct_ behavior?

**In Juicebox** chart should be accurate.

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by wraeth-eth** [comment] 2023-01-27 05:06
Hey @aeolianeth - I am not sure what the problem is with this one 😅 - might need more info on it 🙏

**Comment by tomquirk** [comment] 2023-02-02 01:43
@peripheralist might send this your way as you're working on the vlume chart rebuild.

@wraeth-eth  The issue is that the In Juicebox chart sometimes doesn't match up with the actual amount in the JB treasury on-chain. In this example, the chart is saying there is 3.15 ETH, but there is actually only 0.1774ETH

**Comment by tomquirk** [comment] 2023-02-02 01:44
Might be related to https://github.com/orgs/jbx-protocol/projects/1/views/26?pane=issue&itemId=18502383

**Comment by peripheralist** [comment] 2023-02-09 22:32
is this still reproducible? pretty sure this was fixed

**Comment by tomquirk** [comment] 2023-02-10 00:16
@peripheralist if not, lets close! <3

**Comment by peripheralist** [comment] 2023-02-10 05:31
closing, can reopen if it comes up again

**Closed** 2023-02-10 05:32 UTC
Labels: type:bug, priority:2
