### ISSUE TITLE
Percent slider incorrectly set on token allocation edit

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#1269] opened 2022-06-22 03:02 UTC
## Summary

_A clear and concise description of what the bug is._

## Steps to reproduce

1. Go to reserved token allocation (either on existing project, or via create)
2. Create a token allocation
3. Open existing allocation for edit
4. See error (no slider set, but percent is - see vid)

## Relevant logs and/or screenshots

https://user-images.githubusercontent.com/104132113/174934398-8479fd6d-2d13-4793-8424-c0183bd972e1.mov

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by aeolianeth** [comment] 2022-06-22 03:03
@wraeth-eth possible duplicate of https://github.com/jbx-protocol/juice-interface/issues/1199 ? (but not sure, https://github.com/jbx-protocol/juice-interface/issues/1199 has no details heh. Happy to close https://github.com/jbx-protocol/juice-interface/issues/1199 in favor of this issue, and assign it to FC24)

**Comment by wraeth-eth** [comment] 2022-06-22 03:15
Could be the same by sounds of title - happy for them to be merged

**Closed** 2022-06-27 08:48 UTC
Labels: bug
