### ISSUE TITLE
Website isn't aware of network change events

### ISSUE THREAD

**Issue by LuckyKoala** [jbx-protocol/juice-interface#407] opened 2022-01-20 09:40 UTC
## Description

The website are not awared of network change event, this will bring inconsistency and inconvience to users:

1. Wallet connected to another network, user go to juicebox, this modal pop up
![image](https://user-images.githubusercontent.com/18607651/150303383-1002b3ee-17e2-488c-94c9-6e726f363201.png)

Currently, users who connected with different network will see `switchNetworkModal`. But this modal can't be closed, so users have to switch network through their wallet manually and then refresh the page.

---

2. Wallet connected to expected network, user go to juicebox, switch to other website, come back with different network connected
2.1 user go to dashboard page of arbitrary project
![image](https://user-images.githubusercontent.com/18607651/150310793-2be4fae4-7478-45c8-8b6b-bbcd4ae6e60f.png)
2.2 user click "Connect", both switchNetworkModal and network switch of Blocknative onboard pops up
![image](https://user-images.githubusercontent.com/18607651/150309541-c6af0814-859b-444d-90f2-60c04539a2c8.png)

## Proposal

1. monitor network change event, display and close `switchNetworkModal` accordingly to improve UX.
2. add connect option to this modal, since Blocknative has an onboard API which will pull up the wallet to suggest network change. (check screenshot below)

## Screenshots

![image](https://user-images.githubusercontent.com/18607651/150304790-eb7583a1-83f9-4a51-ae30-0e83c6a5f236.png)
![image](https://user-images.githubusercontent.com/18607651/150305844-3754e1f7-58db-43d9-b70a-5e9920a8a072.png)

**Comment by peripheralist** [comment] 2022-01-27 02:41
duplicate of #290, but leaving it open since @LuckyKoala has some great info here

**Comment by jmilldotdev** [comment] 2022-05-06 14:51
Honestly resolving this seems as easy as removing the switch network modal in `src/App.tsx`. Blocknative seems to handle requesting a network switch and denying the user's transactions with a warning modal that they need to switch out of the box.

Maybe as an additional guard, we could track the connected network and put a warning below the connected address box that the user is not on the correct network.

**Comment by aeolianeth** [comment] 2022-05-07 03:32
@jmilldotdev Is it possible that, when the user changes their wallet network, we can close the modal? That feels like the minimum viable change.

**Comment by aeolianeth** [comment] 2022-05-07 03:45
@jmilldotdev all good, found it https://github.com/jbx-protocol/juice-interface/pull/949

**Comment by aeolianeth** [comment] 2022-05-07 16:46
Reverted the PR: https://github.com/jbx-protocol/juice-interface/pull/962

It caused a runtime exception.

**Closed** 2022-06-24 02:07 UTC
Labels: bug, severity::2
