### ISSUE TITLE
Handle long project websites better

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1471] opened 2022-07-21 06:47 UTC
## Summary

<img width="675" alt="Screen Shot 2022-07-21 at 3 47 32 pm" src="https://user-images.githubusercontent.com/96150256/180147990-07eee9db-006f-484f-9799-0fb73423c88b.png">

Need fix for:
- [ ] preview in create flow
- [ ] project page

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by tomquirk** [comment] 2022-07-24 02:25
Closing, duplicate of https://github.com/jbx-protocol/juice-interface/issues/1452

**Closed by tomquirk** 2022-07-24 02:25 UTC
Labels: type:bug, severity:3
