### ISSUE TITLE
on tool gear press in mobile application UX is completely broken

### ISSUE THREAD

**Issue by benschac** [jbx-protocol/juice-interface#1638] opened 2022-08-01 15:10 UTC
## Summary
If a user tries to click the tool wrench button on mobile the mobile version of the web app is no longer useable.

## Steps to reproduce

1. Go to https://www.juicebox.money/@juicebox
2. Click on a phone browser or in phone view in dev tools
3. clock tools wrench

## Relevant logs and/or screenshots
![CleanShot 2022-08-01 at 11 07 28](https://user-images.githubusercontent.com/2502947/182180718-7c3efe33-fba8-4a33-b38e-a497f791162e.gif)

## Environment

- **Device/OS**: [mobile]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by tomquirk** [comment] 2022-08-01 23:07
Duplicate of https://github.com/jbx-protocol/juice-interface/issues/1568 🙏

**Closed by tomquirk** 2022-08-01 23:07 UTC
Labels: type:bug, ux:project owner
