### ISSUE TITLE
Speeding up launch transaction causes UI to get stuck (not relocated after Tx success) 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#2256] opened 2022-10-17 01:06 UTC
## Summary

<img width="1030" alt="Screen Shot 2022-10-17 at 11 06 16 am" src="https://user-images.githubusercontent.com/96150256/196068894-79546be1-2f10-45f1-9309-02778864e577.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by jmilldotdev** [comment] 2022-10-24 01:48
@peripheralist, seems to be an oddity with the combination of tx speed up + the new transactor, any ideas?

**Comment by peripheralist** [comment] 2022-10-24 02:12
> @peripheralist, seems to be an oddity with the combination of tx speed up + the new transactor, any ideas?

i'd expect the tx history polling to still work fine, since speeding up a tx wouldn't change its tx hash

in the screenshot it looks like the tx failed, which would explain the ui being stuck (though if that's the case we could for sure handle that case better). are we sure the tx succeeded?

if so, my guess is something is wrong with how we're calling `onDone()`/`onConfirmed()` for a tx that was sped up. looks like @aeolianeth just refactored that code a few weeks ago, u got any ideas?

**Comment by jmilldotdev** [comment] 2022-10-24 13:09
Repro'd on goerli prod

<img width="475" alt="image" src="https://user-images.githubusercontent.com/33093632/197532779-36c78c46-0048-48e8-a631-74394d749e78.png">

Successful Tx: https://goerli.etherscan.io/tx/0x6a152b8d1722f2eae017e9f0c679c9c52decfba7ec8938561ba9d916350bc3e4

Project: https://goerli.juicebox.money/v2/p/69

**Comment by wraeth-eth** [comment] 2023-01-20 00:07
This is still a problem with new create flow. Looks to be occurring around the logic in `TxHistoryProvider` where it calls `pollTransaction`. 

When you do a speedup, sometimes `getTransaction` returns null, which causes the onCancel to fire.
I have tried matching rceipts and transactions, as well as tx counts, but still not having any luck unfortunately

**Comment by wraeth-eth** [comment] 2023-01-20 05:10
Going to stop looking at this one for now. I think to solve this we need to move away from polling and probably do something a bit more advanced. I looked at using websocket and was partially successful; however, this gave every single packet available flooding in which is not useful.

**Comment by tomquirk** [comment] 2023-01-22 23:39
Will move it out of the `in dev` column

**Comment by tomquirk** [comment] 2023-02-02 01:43
Maybe we just close this for now.

**Closed by tomquirk** 2023-02-02 01:43 UTC
Labels: type:bug, priority:2
